[build]
  base = "frontEnd"
  command = "bun run build"
  publish = "frontEnd/dist"

[build.environment]
  NETLIFY_USE_BUN = "true"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
